spring:
   datasource:
      url: jdbc:mysql://localhost:3306/webdiary?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 
      driver-class-name: com.mysql.cj.jdbc.Driver
swagger3:
   enable: true
   title: WebDiary2
   description: For WebDiary API
   authHeader: token